### ISSUE TITLE
deply locally problem

### ISSUE THREAD

**Issue by zhilongjia** [flekschas/enhancer-gene-vis#3]
after `npm start`. Type a gene name, the local webserver will crash and show the following: 
![img](https://i.ibb.co/Brq5twZ/Screenshot-20210409220650-1414x198.png)
![img2](https://i.ibb.co/z6s4vLP/Screenshot-20210409220635-984x932.png)

And add `// eslint-disable-next-line` to the section does not work. see ![figure](https://i.ibb.co/pyL6TRx/Screenshot-20210409221257-1239x250.png)

Thank you.

**Comment by flekschas** [comment]
The first thing is just a warning and not important at all.

The second thing seems to be a proper bug. Thanks for finding it! Do you experience the same issues the online version?

**Comment by flekschas** [comment]
FYI, you can drag and drop images directly into the text area so that they show up next to your text :)

**Comment by zhilongjia** [comment]
"Do you experience the same issues the online version?"

It will be a black page with nothing showing (though a refresh will work again).

The `inspect` is as below.

![Screenshot-20210410095040-1826x1001](https://user-images.githubusercontent.com/1230436/114254522-85b7b580-99e2-11eb-8c88-6f6852e89bab.png)

**Comment by flekschas** [comment]
Sorry about the glitch. I'll invest!

**Comment by flekschas** [comment]
Note to myself: this is caused by a recent change in resgen.io

**Comment by flekschas** [comment]
Should be working again. Let me know if you still run into issues
