### ISSUE TITLE
super minor change

### ISSUE THREAD

**Issue by kailashbp** [flekschas/enhancer-gene-vis#6]
This is in the second para of the introduction

"However, enhancers are not always active in every cell type or state. Hence, in reality the looks more like below where Enhancer 1 is entirely inactive in Sample 1 while Sample 2 is inactive in Sample 3." Don't you mean, "Enhancer 2 is inactive in Sample 3"?

**Comment by flekschas** [comment]
Thanks a lot for bringing this up! You're right, this is a type and it should be `Enhancer 2 is inactive...`. I fixed it and will re-deploy.
